import type { Property } from "@/types/domain";

const now = new Date().toISOString();

export const featuredProperties: Property[] = [
  {
    id: "prop-1",
    workspaceId: "workspace-1",
    agentId: "agent-1",
    title: "Residencia Bosque Alto",
    slug: "residencia-bosque-alto",
    publicCode: "SH-001",
    propertyType: "house",
    status: "active",
    operationType: "sale",
    isFeatured: true,
    locationLabel: "Valle del Sol",
    city: "Monterrey",
    state: "Nuevo León",
    countryCode: "MX",
    priceAmount: 12800000,
    currencyCode: "MXN",
    bedrooms: 4,
    bathrooms: 4.5,
    parkingSpots: 3,
    lotAreaM2: 420,
    constructionAreaM2: 510,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop-2",
    workspaceId: "workspace-1",
    agentId: "agent-1",
    title: "Penthouse Santa Fe",
    slug: "penthouse-santa-fe",
    publicCode: "SH-002",
    propertyType: "apartment",
    status: "active",
    operationType: "rent",
    isFeatured: true,
    locationLabel: "Zona corporativa",
    city: "Ciudad de México",
    state: "CDMX",
    countryCode: "MX",
    priceAmount: 78000,
    currencyCode: "MXN",
    bedrooms: 3,
    bathrooms: 3.5,
    parkingSpots: 2,
    constructionAreaM2: 260,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop-3",
    workspaceId: "workspace-1",
    agentId: "agent-2",
    title: "Casa Jardines",
    slug: "casa-jardines",
    publicCode: "SH-003",
    propertyType: "house",
    status: "pending",
    operationType: "sale",
    isFeatured: true,
    locationLabel: "Zona residencial premium",
    city: "Guadalajara",
    state: "Jalisco",
    countryCode: "MX",
    priceAmount: 9450000,
    currencyCode: "MXN",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 2,
    lotAreaM2: 300,
    constructionAreaM2: 340,
    createdAt: now,
    updatedAt: now,
  },
];
